<?php
/**
 * @file
 * Code for the GSB Feature Program Application Finder feature
 */

 /**
  * Implements hook_ctools_plugin_directory().
  */
function gsb_feature_program_app_finder_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 *
 * Define custom theme hooks
 */
function gsb_feature_program_app_finder_theme($existing, $type , $theme, $path) {
  return array(
    'gsb_feature_program_app_finder_program_list' => array(
      'template' => 'templates/gsb-feature-program-app-finder-program-list',
      'file' => 'program_list.theme.inc',
    ),
    'gsb_feature_program_app_finder_program_instance_list' => array(
      'template' => 'templates/gsb-feature-program-app-finder-program-instance-list',
      'file' => 'program_instance_list.theme.inc',
    ),
  );
}

function gsb_feature_program_app_finder_forms($form_id, $args) {
  $forms['program_app_finder'] = array(
    'callback' => 'gsb_feature_program_app_finder_form',
    'callback arguments' => $args,
  );
  return $forms;
}

function gsb_feature_program_app_finder_form($form, &$form_state) {

  $program_nid = '';
  if (!empty($_GET['program'])) {
    $program_nid = $_GET['program'];
  }
  drupal_add_js(array('gsb_feature_program_app_finder' => array('program' => $program_nid)), 'setting');

  $form['app-finder'] = array(
    '#type' => 'container',
  );

  $form['app-finder']['title'] = array(
    '#type' => 'markup',
    '#markup' => '<h4>' . t('Ready to Apply?') . '</h4>'
  );

  $form['app-finder']['programs-text'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="programs-text"></div>'
  );

  $form['app-finder']['programs-instance-title'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="programs-instance-title"></div>'
  );

  $form['app-finder']['programs-instance-deadline'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="programs-instance-deadline"></div>'
  );

  $form['app-finder']['programs-instance-date-select'] = array(
    '#type' => 'select',
    '#title' => '',
    '#options' => array(),
    '#attributes' => array(
      'class' => array('programs-instance-date-select'),
    ),
    '#multiple' => true,
    '#default_value' => array()
  );

  $form['app-finder']['programs-instance-sample-app-form-url'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="programs-instance-sample-app-form-url-wrapper hide_this"><a href="" class="programs-instance-sample-app-form-url" target="_blank">Sample Application</a></div>'
  );

  $form['app-finder']['programs-instance-application-url'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="programs-instance-application-url-wrapper hide_this"><a href="" class="programs-instance-application-url">Apply Online</a></div>'
  );

  $form['app-finder']['programs'] = array(
    '#type' => 'select',
    '#title' => '',
    '#options' => $form_state[0]['programs']['options'],
    '#attributes' => array(
      'class' => array('program-find-app-select'),
    ),
    '#multiple' => true,
    '#default_value' => array()
  );

  $form['app-finder']['programs-disclaim'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="programs-disclaim">' . t('Only programs currently accepting applications are displayed.') . '</div>'
  );

  $form['app-finder']['programs-different'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="programs-different hide_this"><span>Or </span><a href="" class="programs-different-link">Select a Different Program</a></div>',
  );

  drupal_add_js(drupal_get_path('module', 'isotopify') . '/js/jquery.multiple.select.js');
  drupal_add_css(drupal_get_path('module', 'isotopify') . '/css/multiple-select.css');
  drupal_add_js(drupal_get_path('module', 'gsb_feature_program_app_finder') . '/js/gsb_feature_program_app_finder.js');
  drupal_add_css(drupal_get_path('module', 'gsb_feature_program_app_finder') . '/css/gsb_feature_program_app_finder.css');

  return $form;
}